name: skripsi_ba_parkir_desktop
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  cloud_firestore: ^4.12.2
  cupertino_icons: ^1.0.2
  dio: ^5.3.3
  dotted_border: ^2.1.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.21.0
  firebase_database: ^10.3.3
  firebase_storage: ^11.4.1
  flutter:
    sdk: flutter
  get: 4.6.6
  google_maps_flutter: ^2.5.0
  http: ^1.1.0
  image_picker: ^1.0.4
  intl: ^0.18.1
  process: ^5.0.1
  qr_flutter: ^4.1.0
  rxdart: ^0.27.7
  shared_preferences: ^2.0.10
  web_socket_channel: ^2.2.0

dev_dependencies:
  flutter_lints: 3.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/bg/
    - assets/logo/
    - assets/lotties/
    - assets/img/
